name: puby
description: Run commands in all projects in the current directory. Handle monorepos with ease.
version: 1.38.4
homepage: https://github.com/Rexios80/puby

environment:
  sdk: ^3.0.0

dependencies:
  yaml: ^3.1.1
  pubspec_parse: ^1.2.1
  path: ^1.8.1
  pub_update_checker: ^1.2.0
  flutter_tools_task_queue: ^1.0.0
  dart_pub: 0.0.6
  pub_semver: ^2.1.4
  io: ^1.0.4
  meta: ^1.17.0

dev_dependencies:
  test: ^1.20.2
  rexios_lints: ^17.0.2

executables:
  puby: puby
